### ISSUE TITLE
is this still actively maintained?

### ISSUE THREAD

**Issue by rubenarslan** [ddionrails/r2ddi#64]
I'm asking because I'd be curious whether you plan on integrating with https://github.com/hadley/haven in the future. My work on https://github.com/rubenarslan/codebook would benefit from that.

**Comment by mhebing** [comment]
Ruben, sorry but there are currently no plans to further maintain the r2ddi package. We switched to Python (Pandas) for most of our projects and started to re-implement the functionality you found in r2ddi in Python: https://github.com/ddionrails/ddi.py
